### ISSUE TITLE
source: not found [Fix]

### ISSUE THREAD

**Issue by dropitlikecross** [nsauter/nextcloud-installer#1]
```
sudo ./install.sh 
./install.sh: 6: ./install.sh: source: not found
```

Running ubuntu 18.04. Resolved by changing `#/bin/sh` to `#!/bin/bash` in line1 of install.sh

**Comment by nsauter** [comment]
Thanks for your input. I tried it on ubuntu 18.04 an it worked flawlessly. Are you able to create a pull request or should i fix it?

**Comment by nsauter** [comment]
I commited your fix. Closing this issue now.
